Quiz/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Quiz_Test.urls'))
]

Quiz_Test/urls.py
from django.urls import path
from .views import Home,List_quiz,Quiz,Save_quiz_answer,Result_quiz,Correct_Answers


urlpatterns = [
    path('',Home,name='HOME'),
    path('list_quiz/<str:pk>',List_quiz,name='LIST_QUIZ'),
    path('quiz/<str:pk>',Quiz,name='QUIZ'),
    path('corrent_asnwer/<str:pk>',Correct_Answers,name='ANSWER'),
    path('save_answer',Save_quiz_answer,name='SAVE_QUIZ_ANSWER'),
    path('result/<str:pk>',Result_quiz,name='RESULT_QUIZ')
]

Quiz_Test/models.py
from django.db import models

class Category(models.Model):
    title = models.fields.CharField(max_length=55,primary_key=True)

    def __str__(self) -> str:
        return self.title

class Detail_Vote(models.Model):
    
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    title = models.fields.CharField(blank=False,max_length=59)
    date_create = models.fields.DateTimeField(auto_now_add=True)
    time = models.fields.IntegerField()
    start_qustion  = models.fields.IntegerField()
    end_qustion  = models.fields.IntegerField()
    type_answer =[
        (4,"4 chocies"),
        (5,"5 chocies"),
        (6,"6 chocies"),
        (7,"7 chocies"),
        (8,"8 chocies")
                ]
    type_choices = models.SmallIntegerField(choices=type_answer,default=4)

    def __str__(self) -> str:
        return f'{self.category.title} {self.title}'

class Answer(models.Model):

    vote = models.ForeignKey(Detail_Vote,on_delete=models.CASCADE)
    number = models.fields.CharField(max_length=4,primary_key=True)
    answer = models.fields.IntegerField(default=0)
    def __str__(self) -> str:
        return f'[{self.vote.title}] [ number  {self.number} : answer {self.answer} ]'

class Correct_Answer(models.Model):

    vote = models.ForeignKey(Detail_Vote,on_delete=models.CASCADE)
    number = models.fields.CharField(max_length=4,primary_key=True)
    answer = models.fields.IntegerField(default=0)
    def __str__(self) -> str:
        return f'[{self.vote.title}] [ number  {self.number} : answer {self.answer} ]'

Quiz_Test/views.py
from django.shortcuts import redirect, render , HttpResponse
from .models import Category,Detail_Vote,Answer,Correct_Answer

def Home(request):
    template = 'html/home.html'
    context = {'category':Category.objects.all()}
    return render(request,template,context)

def List_quiz(request,pk):
    template = 'html/list_quiz.html'
    context = {'list_quiz':Detail_Vote.objects.filter(category=pk)}
    return render(request,template,context)

def Quiz(request,pk):
    template = 'html/quiz.html'
    data = Detail_Vote.objects.get(pk = pk)
    total = [i for i in range(data.start_qustion,data.end_qustion+1)]
    choices = [i for i in range(1,data.type_choices+1)]
    context = {'range':total,'choices':choices,'pk':data.pk,'time':data.time,'type':'answer'}
    return render(request,template,context)

def Correct_Answers (request,pk):

    template = 'html/set_correct_asnwer.html'
    data = Detail_Vote.objects.get(pk = pk)
    total = [i for i in range(data.start_qustion,data.end_qustion+1)]
    list_quiz = {}
    type_choices = [i for i in range(1,data.type_choices+1)]
    for i in range(data.start_qustion,data.end_qustion+1):
        choices = type_choices.copy()
        try:
            
            choice = Correct_Answer.objects.get(vote = data , number = i)
            answer =choice.answer

            if answer == 0:
                list_quiz[i] = choices

            else:    
                index =  (answer -1) ##index of answer equil :  number of answer - 1 
                choices[index] = 'True' 
                list_quiz[i] = choices
              

        except  :
            list_quiz[i] = choices

    context = {'Answers':list_quiz,'pk':data.pk,'time':data.time,'type':'correct_answer',}
    return render(request,template,context)

def Save_quiz_answer(request):

    if request.method == 'POST':

        pk = request.POST['quiz_pk']
        vote = Detail_Vote.objects.get(pk=pk)

        if 'answer' in request.POST :
            
            for item , answer in request.POST.items():
                item = str(item).replace('questoin-','')
                
                if str(item).isdigit() :
                    item = int(item)
                    
                    try:
                        vote_quiz = Answer.objects.get(vote = vote , number = item ) 
                        vote_quiz.answer = answer
                        vote_quiz.save()
                    except:
                        Answer(vote = vote , number = item , answer = answer ).save() 


        elif 'correct_answer' in request.POST:
            
            for item , answer in request.POST.items():
                item = str(item).replace('questoin-','')
            
                if str(item).isdigit() :
                    item = int(item)
            
                    try:
                        vote_quiz = Correct_Answer.objects.get(vote = vote , number = item ) 
                        vote_quiz.answer = answer
                        vote_quiz.save()
                    except:
                        Correct_Answer(vote = vote , number = item, answer = answer).save() 
    
    return redirect(Home)

def Result_quiz(request,pk):
    data = {}
    template = 'html/result.html'
    vote = Detail_Vote.objects.get(pk=pk)
    total_Correct = 0
    total_worng = 0
    total_none = 0
    
    for i in range(vote.start_qustion,vote.end_qustion+1):
        choices = [None,None,None,None]
        status_answers = False
        
        try:
            answer = Answer.objects.get(vote = vote , number = i)
            answer = answer.answer
            index =  (answer -1) ##index of answer equil :  number of answer - 1 
            choices[index] = 'False' 
            data[i] = choices
            status_answers = True
        except:
            pass
        
        try:
            correct = Correct_Answer.objects.get(vote = vote , number = i)
            answer = correct.answer
            index =  (answer -1) ##index of answer equil :  number of answer - 1 
            if 'False' in choices:
                index_False = choices.index('False')
                # print(index_False , index)
                if index == index_False:
                    choices[index] = 'True/False'      
                else:
                    choices[index] = 'True'      
            else:
                choices[index] = 'True'
            data[i] = choices
            
            status_answers = True
        except:
            pass

        if status_answers == False:
            data[i] = choices
            total_none +=1
            # print(f'FALSE : {i}')
        else:
            if 'True/False' in data[i]:
                total_Correct +=1
            else:
                if 'False' not in data[i] :
                    total_none +=1
                else:
                    total_worng +=1
            

    # for i , n in data.items():
    #     print(i,n)

    # print(f'{total_Correct:} {total_worng:} {total_none:}')

    context = {"data":data,'worng':total_worng,'Correct':total_Correct,'total_none':total_none}
    return render(request,template,context)

Quiz_Test/templates/html/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>برنامه آزمون من </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>


<body dir='ltr'>

<div class="jumbotron text-center">
  <h1>سوالات چهار گزینه ای</h1>
  </h4><p>فهرست کتاب ها</p> </h4>
</div>


 <ul class="list-group">
  {% for cat in category %}
    <li class="list-group-item d-flex justify-content-between align-items-center" >
      <a href="{% url "LIST_QUIZ" cat.title %}">{{cat.title}}</a>
      <span class="badge badge-primary badge-pill">{{cat.detail_vote_set.count}}</span>
    </li>
  {%endfor%}
</ul>



</body>

</html>

Quiz_Test/templates/html/list_quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>لیست آزمون ها</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>


<body  >

<div class="jumbotron text-center">
  <h1>سوالات چهار گزینه ای</h1>
  <h4><p>فهرست فصل ها </p> </h4>
</div>
<center>
{%for item in list_quiz%}
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{item.title}}</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">زمان آزمون :  {{item.time}} دقیقه </li>
    <li class="list-group-item">شروع و پایان سوالات : {{item.start_qustion}} ~ {{item.end_qustion}}</li>
    <li class="list-group-item">زمان ساخت آزمون : {{item.date_create}}</li>
  </ul>
  <div class="card-body">
    <a href="{% url 'QUIZ' item.pk  %}" class="card-link"> [شروع]</a>
    <a href="{% url 'ANSWER' item.pk  %}" class="card-link"> [تصحیح]</a>
    <a href="{% url 'RESULT_QUIZ' item.pk  %}" class="card-link"> [نتیجه]</a>
  </div>
</div>
<br>
{%endfor%}
</center>
</body>

</html>

Quiz_Test/templates/html/quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>آزمون</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>


<body  >

<div class="jumbotron text-center">
  <!-- <h1>آزمون</h1> -->
  <h4><p> لیست سوالات </p> <p>زمان آزمون {{time}} دقیقه </p></h4>
</div>

<form style='text-align-last: center;' action="{% url 'SAVE_QUIZ_ANSWER' %}" method="POST">

    {%csrf_token%}
    <input type="hidden" name="quiz_pk" value="{{pk}}">
    <input type="hidden" name="{{type}}">
    {%for x in range %}

    <label for="qustion{{x}}" style="margin-right: 25px;">{{x}} : </label>
      <div class="form-check form-check-inline" id="question{{x}}" onmousedown="changeColor('question{{x}}')" >

        {%for i in choices %}

            <!-- <label class="form-check-label" for="inlineRadio">{{i}}</label> -->
            <input class="form-check-input" type="radio"  id="inlineRadio" value="{{i}}" name="questoin-{{x}}" style="height:20px; width:20px; margin-right: 8px;margin-left: 8px;margin-top: 4px;">

          {%endfor%}

      </div>
      <br><hr>

    {%endfor%}

    <div class="col-auto">
      <button type="submit" class="btn btn-primary" style="margin-bottom: 5%;">ارسال</button>
    </div>

</form>

</body>

</html>

Quiz_Test/templates/html/result.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>نتیجه آزمون</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>


<body  >

<div class="jumbotron text-center">
  <!-- <h1>آزمون</h1> -->
  <h4>
      <p> جواب سوالات</p> <p>تعداد جواب های صحیح : {{Correct}} </p>
      <p>تعداد جواب های غلط : {{worng}}</p>
      <p>تعداد جواب های داد نشده : {{total_none}}</p>

      <div  class="form-check form-check-inline" id="question">
          <label for="full-corrent" style="margin-right: 6px;">Best answer : </label>
          <input class="form-check-input" type="checkbox" id="full-corrent" style=" outline:3px solid indigo; " value=""  checked >
      </div>
        <br>

      <div  class="form-check form-check-inline" id="question">
        <label for="corrent" style="margin-right: 6px;">Corrent : </label>
        <input class="form-check-input" type="checkbox" id="corrent" style=" outline:3px solid green; " value=""  checked >
      </div>
        <br>

      <div  class="form-check form-check-inline" id="question"></div>
          <label for="worng" style="margin-right: 25px;" >Worng : </label>
          <input class="form-check-input" type="checkbox" id="worng" style=" outline:3px solid red; " value=""  checked >
      </div>
</h4>
</div>
<center>
    {%csrf_token%}
    {% for number , answers in data.items%}
    <div  class="form-check form-check-inline" id="question">
        <h5><label style="margin-right: 12px; margin-top: 13px;" for="question">{{number}} : </label></h5>
        {% for status in answers%}

          {% if status == "True" %} 
          <input class="form-check-input" type="checkbox" id="inlineCheckbox1" style=" outline:3px solid green;inline; height: 25px; width: 25px; " value="{{status}}"  checked >
          {%endif%}

          {% if status == "True/False" %} 
          <input class="form-check-input" type="checkbox" id="inlineCheckbox1" style=" outline:3px solid indigo; height: 25px; width: 25px; " value="{{status}}"  checked >
          {%endif%}

          {% if status == "False" %} 
          <input class="form-check-input" type="checkbox" id="inlineCheckbox1" style=" outline:3px solid red; height: 25px; width: 25px; " value="{{status}}" checked >
          {%endif%}

          {% if status == None %} 
          <input class="form-check-input" type="checkbox" id="inlineCheckbox1" style="height: 25px; width: 25px; " value="{{status}}" >
          {%endif%}

          <!-- <label class="form-check-label" for="inlineCheckbox1">{{status}}</label> -->
             
        {%endfor%}
    </div>
    <br><hr>
    {%endfor%}
</center>
</body>

</html>

Quiz_Test/templates/html/set_correct_asnwer.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>آزمون</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>


<body  >

<div class="jumbotron text-center">
  <!-- <h1>آزمون</h1> -->
  <h4><p> لیست سوالات </p> <p>زمان آزمون {{time}} دقیقه </p></h4>
</div>

<form style='text-align-last: center;' action="{% url 'SAVE_QUIZ_ANSWER' %}" method="POST">

    {%csrf_token%}
    <input type="hidden" name="quiz_pk" value="{{pk}}">
    <input type="hidden" name="{{type}}">
    {%for number , answers in Answers.items %}

    <label for="qustion{{number}}" style="margin-right: 25px;">{{number}} : </label>
      <div class="form-check form-check-inline" id="question{{number}}" onmousedown="changeColor('question{{number}}')" >

        {%for i in answers %}

            <!-- <label class="form-check-label" for="inlineRadio">{{i}}</label> -->
            <input class="form-check-input" type="radio"  id="inlineRadio" value=" {{forloop.counter}}" name="questoin-{{number}}" style="height:20px; width:20px; margin-right: 8px;margin-left: 8px;margin-top: 4px;" {% if i == 'True'%} checked {% endif%} > 

          {%endfor%}

      </div>
      <br><hr>

    {%endfor%}

    <div class="col-auto">
      <button type="submit" class="btn btn-primary" style="margin-bottom: 5%;">ارسال</button>
    </div>

</form>

</body>

</html>